### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\7520\Downloads\vezeeta_doctors3.csv")

In [3]:
df.head()

,page,name,description,Speciality,address,fee,rating,reviews_count,waiting_time,profile_url,image_url,about_doctor,symptoms_text,subspecialties_text
0,1,Mohamed Fateen Anous,Consultant of General and Laproscopic Surgery,General Surgery,New Cairo,600.0,5,37.0,Waiting Time : 26 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-f...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Consultant of general and laparoscopic surgery,"Pilonidal Cyst, Intestinal Obstruction, Fistul...","Obesity Surgery, Abdominal Surgery, Adult Gast..."
1,1,Heba Hassan Hadhoud,"Specialist in oral and dental medicine, implan...",Dentistry,El-Rehab,200.0,5,608.0,Waiting Time : 14 Minutes,https://www.vezeeta.com/en/dr/doctor-heba--has...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Bruxism, Teeth whitening, TMJ Disorder, Molar ...","Pediatric Dentistry, Cosmetic Dentistry, Endod..."
2,1,Hoda Beder,"Consultant of Obstetrics, Gynecology and Infer...",Reproductive Medicine & Infertility,Tanta,150.0,5,131.0,Waiting Time : 22 Minutes,https://www.vezeeta.com/en/dr/doctor-hoda-bede...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Dr. Huda Badir\n\n-PhD in Obstetrics and Gynec...,"Vaginal Dryness, Pregnancy, Placental Abruptio...","Gynaecologic Oncological Surgery, Obstetrics, ..."
3,1,Medhat higazi,"Specialist in root canal treatment, cosmetic d...",Dentistry,New Cairo,400.0,5,605.0,Waiting Time : 12 Minutes,https://www.vezeeta.com/en/dr/clinic-medhat--h...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"‎ -Bachelor of Oral and Dental Medicine, Ain S...","Bruxism, Teeth whitening, Molar Pain, Bleeding...","Cosmetic Dentistry, Endodontics, Periodontics,..."
4,1,Kareem Abdelfattah,Dental Cosmetic and restorative Specialist,Dentistry,El-Sheikh Zayed,400.0,5,84.0,Waiting Time : 9 Minutes,https://www.vezeeta.com/en/dr/doctor-kareem-ab...,https://cdn-dr-images.vezeeta.com/Assets/Image...,- Dr. Kareem Abdel Fattah holds a British fell...,"Bruxism, Teeth whitening, Molar Pain, Bleeding...","Cosmetic Dentistry, Endodontics, Periodontics,..."

### Address column cleaning

In [ ]:

mapping = {
    'أجا': 'Aga',
    'إمبابة': 'Imbaba',
    'اشمون': 'Ashmun',
    'الإبراهيمية': 'El-Ibrahimia',
    'التجمع': 'El-Rehab',
    'الدقي والمهندسين': 'Dokki and Mohandessin',
    'الرحاب': 'El-Rehab',
    'الزقازيق': 'El-Zagazig',
    'الزيتون': 'El-Zaitoun',
    'السيدة زينب': 'El-Sayed Zaïnab',
    'السيوف': 'El-Seyouf',
    'الشروق': 'El-Shorouk',
    'الشيخ زايد': 'El-Sheikh Zayed',
    'العامية': 'El-Amreya',
    'العباسية': 'El-Abbasia',
    'العجمي': 'El-Agamy',
    'العجوزة': 'El-Agouza',
    'العصافرة': 'El-Asafra',
    'المحلة الكبرى': 'Mahalla',
    'المرج': 'El-Marg',
    'المطرية': 'El-Matareya',
    'المعادي': 'El-Maadi',
    'المقطم': 'El-Mokattam',
    'المنصورة': 'El-Mansoura',
    'المنيل': 'El-Manyal',
    'الهرم': 'El-Haram',
    'الورديان': 'El-Werdeyan',
    'بوكلي': 'Bulky',
    'حدائق الأهرام': 'Hadayek El-Ahram',
    'حدائق القبة': 'Hadayek El-Kobba',
    'حدائق حلوان': 'Hadayek Helwan',
    'حلوان': 'Helwan',
    'دكرنس': 'Dekernes',
    'دمنهور': 'Damanhur',
    'سموحة': 'Smouha',
    'سيدي بشر': 'Sidy Bishr',
    'سيدي جابر': 'Sidy Gaber',
    'شبرا': 'Shoubra',
    'شبين الكوم': 'Shibin El-Kom',
    'طنطا': 'Tanta',
    'عين شمس': 'Ain Shams',
    'فيصل': 'Faisal',
    'فيكتوريا': 'Victoria',
    'قليوب': 'Qalyoub',
    'كفر عبده': 'Kafr Abdouh',
    'لوران': 'Loran',
    'محرم بيك': 'Moharam Bek',
    'محطة الرمل': 'Mahatet El-Raml',
    'مدينة العبور': 'El-Obour City',
    'مدينة الغردقة': 'Hurghada City',
    'مدينة الفيوم': 'El-Fayoum city',
    'مدينة بني سويف': 'Beni Suef City',
    'مدينة دمياط الجديدة': 'Damietta El Gadeeda',
    'مدينة نصر': 'Nasr City',
    'مدينتي': 'Madinaty',
    'مركز أسيوط': 'Assiut city',
    'مركز المنيا': 'El Minya City',
    'مركز كفر الزيات': 'Kafr El Zayat',
    'مصر الجديدة': 'Heliopolis',
    'منيا القمح': 'Menya El-Kamh',
    'ميامي': 'Miamy',
    'ميدان الجيزة': 'El-Giza',
    'وسط البلد': 'West El-Balad'
}

# Replace Arabic with English - using correct column name 'address'
df['address'] = df['address'].replace(mapping)

In [12]:
df['address'].unique().tolist()

['New Cairo',
 'El-Rehab',
 'Tanta',
 'El-Sheikh Zayed',
 'El-Azarita',
 '6th of October',
 'El-Mokattam',
 'Sidy Bishr',
 'Nasr City',
 'West El-Balad',
 'Esna',
 'El-Shorouk',
 'El-Mansoura',
 'Madinaty',
 'Hadayek Helwan',
 'El-Seyouf',
 'El-Zagazig',
 'El-Abbasia',
 'Heliopolis',
 'Ain Shams',
 'Hadayek El-Ahram',
 'El-Obour City',
 'Dokki and Mohandessin',
 'El-Marg',
 'New Nozha',
 'Miamy',
 'Shoubra El-Kheima',
 'Faisal',
 'Masr El-Kadima',
 'Cleopatra',
 'Mahatet El-Raml',
 'North Coast',
 'Assiut city',
 'Shibin El-Kom',
 'Smouha',
 'El-Maadi',
 'El-Agamy',
 'El-Manyal',
 'El-Giza',
 'El-Fayoum city',
 'Suez City',
 'Moharam Bek',
 'Mahalla',
 'El-Zaitoun',
 'Sporting',
 'Shoubra',
 'El-Haram',
 'Fleming',
 'Hurghada City',
 'Sadat City',
 'Bakos',
 'Badr City',
 'Hadayek El-Kobba',
 'El-Sayeda Zainab',
 'Banha',
 'Damietta El Gadeeda',
 'Fakous',
 'Loran',
 'Helwan',
 'El Minya City',
 'El-Ibrahimia',
 'Sohag City',
 'Hadayek El Maadi',
 'Birket El Sabea',
 'Victoria',
 '10th of Ramadan',
 'Imbaba',
 'El-Zamalek',
 'Kafr El sheikh City',
 'El-Agouza',
 'Luxor City',
 'El Salam City',
 'El-Ismailia city',
 'Port Said City',
 'Janaklees',
 'Glym',
 'El-Montazah',
 'El-Mandara',
 'El-Matareya',
 'مدينة بنى سويف',
 'العاشر من رمضان ',
 'Abou Keir',
 'Roshdy',
 'El-Asafra',
 'Sidy Gaber',
 'Abu Hammad',
 'Damietta City',
 'New Giza',
 'Samannoud',
 'El-Amreya',
 'العامرية',
 'بولكلي',
 'El Senbellawein',
 'Dar El-Salam',
 'Damanhur',
 'Beni Suef City',
 'Qena City',
 'Aga',
 'Kafr El Zayat',
 'Stanley',
 'Moustafa Kamel',
 'Camp Caesar',
 'Zizenia',
 'Mit Ghamr',
 'Bulkly',
 'Future City',
 'Shirbin',
 'El-Badrashin',
 'El Qanater El Khayreya',
 'Dekernes',
 'Qalyoub',
 ' مدينة السلام',
 'Menya El-Kamh',
 'Aswan',
 'Shibin Al Qanater',
 'Kafr Abdouh',
 'El-Mansheyah',
 'kafr El dawar',
 'Saba Basha',
 'El-Hawamdeya',
 '6 اكتوبر',
 'فيصل ',
 'Hadayek October',
 'Menouf',
 'Marsa Matrouh',
 'Boulaq El Dakrour',
 'El-Shatby',
 'Belbes',
 'Quwaysna',
 'San Stefano',
 'Ashmun',
 'Itay El Barud',
 'El Shohada',
 'El-Sayed Zaïnab',
 'Belkas',
 'Abnub',
 'El-Werdeyan',
 'El-Kattameya',
 nan,
 'Borg el-Arab',
 'Manfalut',
 'Port Fouad',
 'Kom Ombo',
 'Dayrout',
 'Ibsheway']

In [13]:
df['address'].unique()

array(['New Cairo', 'El-Rehab', 'Tanta', 'El-Sheikh Zayed', 'El-Azarita',
       '6th of October', 'El-Mokattam', 'Sidy Bishr', 'Nasr City',
       'West El-Balad', 'Esna', 'El-Shorouk', 'El-Mansoura', 'Madinaty',
       'Hadayek Helwan', 'El-Seyouf', 'El-Zagazig', 'El-Abbasia',
       'Heliopolis', 'Ain Shams', 'Hadayek El-Ahram', 'El-Obour City',
       'Dokki and Mohandessin', 'El-Marg', 'New Nozha', 'Miamy',
       'Shoubra El-Kheima', 'Faisal', 'Masr El-Kadima', 'Cleopatra',
       'Mahatet El-Raml', 'North Coast', 'Assiut city', 'Shibin El-Kom',
       'Smouha', 'El-Maadi', 'El-Agamy', 'El-Manyal', 'El-Giza',
       'El-Fayoum city', 'Suez City', 'Moharam Bek', 'Mahalla',
       'El-Zaitoun', 'Sporting', 'Shoubra', 'El-Haram', 'Fleming',
       'Hurghada City', 'Sadat City', 'Bakos', 'Badr City',
       'Hadayek El-Kobba', 'El-Sayeda Zainab', 'Banha',
       'Damietta El Gadeeda', 'Fakous', 'Loran', 'Helwan',
       'El Minya City', 'El-Ibrahimia', 'Sohag City', 'Hadayek El Maadi',
       'Birket El Sabea', 'Victoria', '10th of Ramadan', 'Imbaba',
       'El-Zamalek', 'Kafr El sheikh City', 'El-Agouza', 'Luxor City',
       'El Salam City', 'El-Ismailia city', 'Port Said City', 'Janaklees',
       'Glym', 'El-Montazah', 'El-Mandara', 'El-Matareya',
       'مدينة بنى سويف', 'العاشر من رمضان ', 'Abou Keir', 'Roshdy',
       'El-Asafra', 'Sidy Gaber', 'Abu Hammad', 'Damietta City',
       'New Giza', 'Samannoud', 'El-Amreya', 'العامرية', 'بولكلي',
       'El Senbellawein', 'Dar El-Salam', 'Damanhur', 'Beni Suef City',
       'Qena City', 'Aga', 'Kafr El Zayat', 'Stanley', 'Moustafa Kamel',
       'Camp Caesar', 'Zizenia', 'Mit Ghamr', 'Bulkly', 'Future City',
       'Shirbin', 'El-Badrashin', 'El Qanater El Khayreya', 'Dekernes',
       'Qalyoub', ' مدينة السلام', 'Menya El-Kamh', 'Aswan',
       'Shibin Al Qanater', 'Kafr Abdouh', 'El-Mansheyah',
       'kafr El dawar', 'Saba Basha', 'El-Hawamdeya', '6 اكتوبر', 'فيصل ',
       'Hadayek October', 'Menouf', 'Marsa Matrouh', 'Boulaq El Dakrour',
       'El-Shatby', 'Belbes', 'Quwaysna', 'San Stefano', 'Ashmun',
       'Itay El Barud', 'El Shohada', 'El-Sayed Zaïnab', 'Belkas',
       'Abnub', 'El-Werdeyan', 'El-Kattameya', nan, 'Borg el-Arab',
       'Manfalut', 'Port Fouad', 'Kom Ombo', 'Dayrout', 'Ibsheway'],
      dtype=object)

In [15]:
len(df['address'].unique())

145

In [20]:
import re
arabic_pattern = re.compile(r'[\u0600-\u06FF]+')
arabic_addresses = df[df['address'].str.contains(arabic_pattern, na=False)]['address'].unique()
if len(arabic_addresses) == 0:
    print("All Arabic addresses have been successfully replaced with English.")
else:
    print("Remaining Arabic addresses:")
    print(arabic_addresses)

All Arabic addresses have been successfully replaced with English.

In [21]:
df['address'].unique()

array(['New Cairo', 'El-Rehab', 'Tanta', 'El-Sheikh Zayed', 'El-Azarita',
       '6th of October', 'El-Mokattam', 'Sidy Bishr', 'Nasr City',
       'West El-Balad', 'Esna', 'El-Shorouk', 'El-Mansoura', 'Madinaty',
       'Hadayek Helwan', 'El-Seyouf', 'El-Zagazig', 'El-Abbasia',
       'Heliopolis', 'Ain Shams', 'Hadayek El-Ahram', 'El-Obour City',
       'Dokki and Mohandessin', 'El-Marg', 'New Nozha', 'Miamy',
       'Shoubra El-Kheima', 'Faisal', 'Masr El-Kadima', 'Cleopatra',
       'Mahatet El-Raml', 'North Coast', 'Assiut city', 'Shibin El-Kom',
       'Smouha', 'El-Maadi', 'El-Agamy', 'El-Manyal', 'El-Giza',
       'El-Fayoum city', 'Suez City', 'Moharam Bek', 'Mahalla',
       'El-Zaitoun', 'Sporting', 'Shoubra', 'El-Haram', 'Fleming',
       'Hurghada City', 'Sadat City', 'Bakos', 'Badr City',
       'Hadayek El-Kobba', 'El-Sayeda Zainab', 'Banha',
       'Damietta El Gadeeda', 'Fakous', 'Loran', 'Helwan',
       'El Minya City', 'El-Ibrahimia', 'Sohag City', 'Hadayek El Maadi',
       'Birket El Sabea', 'Victoria', '10th of Ramadan', 'Imbaba',
       'El-Zamalek', 'Kafr El sheikh City', 'El-Agouza', 'Luxor City',
       'El Salam City', 'El-Ismailia city', 'Port Said City', 'Janaklees',
       'Glym', 'El-Montazah', 'El-Mandara', 'El-Matareya',
       'Beni Suef City', 'Abou Keir', 'Roshdy', 'El-Asafra', 'Sidy Gaber',
       'Abu Hammad', 'Damietta City', 'New Giza', 'Samannoud',
       'El-Amreya', 'Al Amiriyah', 'Bolkly', 'El Senbellawein',
       'Dar El-Salam', 'Damanhur', 'Qena City', 'Aga', 'Kafr El Zayat',
       'Stanley', 'Moustafa Kamel', 'Camp Caesar', 'Zizenia', 'Mit Ghamr',
       'Bulkly', 'Future City', 'Shirbin', 'El-Badrashin',
       'El Qanater El Khayreya', 'Dekernes', 'Qalyoub',
       'Madinat Al Salam', 'Menya El-Kamh', 'Aswan', 'Shibin Al Qanater',
       'Kafr Abdouh', 'El-Mansheyah', 'kafr El dawar', 'Saba Basha',
       'El-Hawamdeya', 'Hadayek October', 'Menouf', 'Marsa Matrouh',
       'Boulaq El Dakrour', 'El-Shatby', 'Belbes', 'Quwaysna',
       'San Stefano', 'Ashmun', 'Itay El Barud', 'El Shohada',
       'El-Sayed Zaïnab', 'Belkas', 'Abnub', 'El-Werdeyan',
       'El-Kattameya', nan, 'Borg el-Arab', 'Manfalut', 'Port Fouad',
       'Kom Ombo', 'Dayrout', 'Ibsheway'], dtype=object)

In [26]:
df[df['address'].isnull()]

,page,name,description,Speciality,address,fee,rating,reviews_count,waiting_time,profile_url,image_url,about_doctor,symptoms_text,subspecialties_text
12627,1280,Yosef yonis,"Consultant Vascular Surgery, Peripheral Cathet...",Vascular Surgery,NaN,500.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-yosef-yon...,https://cdn-dr-images.vezeeta.com/Assets/Image...,vasculer surgery consultant,NaN,"Pediatric Vascular Surgery, Adult Vascular Sur..."
14809,1500,Mohamed AL Hawy,specialist In Internal Medicine and emergency,Internal Medicine,NaN,70.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mohamed-e...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Specialist In Internal medicine And Emergency,NaN,"Adult Internal Medicine, Infectious Diseases"

In [ ]:
df['address'].dropna(inplace=True)

In [30]:
df[df['page']==6]

,page,name,description,Speciality,address,fee,rating,reviews_count,waiting_time,profile_url,image_url,about_doctor,symptoms_text,subspecialties_text
50,6,I Smile clinic,dentist,Dentistry,El-Obour City,250.0,5,326.0,Waiting Time : 10 Minutes,https://www.vezeeta.com/en/dr/Center-I-Smile--...,https://cdn-dr-images.vezeeta.com/Assets/Image...,High standard clinic with the top technologies...,"Teeth whitening, Molar Pain, Bleeding Gums, Ro...","Pediatric Dentistry, Cosmetic Dentistry, Endod..."
51,6,Moataz Abdelkhaliq,specialist,Dentistry,Shoubra El-Kheima,200.0,5,483.0,Waiting Time : 19 Minutes,https://www.vezeeta.com/en/dr/doctor-moataz-as...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Dentist specialized in fixed prosthodontics , ...",NaN,"Pediatric Dentistry, Orthodontics, Endodontics..."
52,6,abdulrahman ashraf,"Specialist in ear, nose, and throat surgery at...",ENT,Faisal,250.0,5,12.0,Waiting Time : 11 Minutes,https://www.vezeeta.com/en/dr/doctor-abdalrahm...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"- Specialist in Ear, nose and throat surgery a...","Snoring, Tonsillitis, Sneezing, Vertigo, Throa...","Adult Ear, Nose and Throat, Adult Ear, Nose an..."
53,6,Loai Mohammed,"Specialist in Oral Medicine, Orthodontics, Den...",Dentistry,New Cairo,300.0,5,33.0,Waiting Time : 16 Minutes,https://www.vezeeta.com/en/dr/doctor-loai-moha...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Bruxism, TMJ Disorder, Molar Pain, Bleeding Gu...","Adult Dentistry, Implantology, Pediatric Denti..."
54,6,Mohamed Gamal Omr,"Specialist Of Obstetrics and gynecology, infer...",Reproductive Medicine & Infertility,Madinaty,600.0,5,64.0,Waiting Time : 11 Minutes,https://www.vezeeta.com/en/dr/Doctor-Mohamed-G...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"- Specialist in Obstetrics, Gynecology, and La...","Vaginal Dryness, Dilation Of The Cervix, Pain ...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
55,6,abdelhakeem samir,Cardiology & vascular disease specialist,Cardiology,Masr El-Kadima,300.0,5,8.0,Waiting Time : 40 Minutes,https://www.vezeeta.com/en/dr/doctor-abdelhake...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"-I am Dr. Abdelhakeem Samir, a cardiology and ...","Heart Attack, Convulsions, Numbness Of The Per...",Adult Cardiology
56,6,Asem mohsen,"Specialist in general surgery, laparoscopic su...",General Surgery,Ain Shams,300.0,5,3.0,Waiting Time : 10 Minutes,https://www.vezeeta.com/en/dr/doctor-asem-alsu...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Pilonidal Cyst, Fistula, Painful Lump, Pilonid...","Pediatric General Surgery, Obesity Surgery, Ab..."
57,6,Mostafa Yousef Khaleef,Pediatric surgery consultant - Al Azhar Univer...,Pediatrics,Nasr City,450.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mostafa-y...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,NaN,"Pediatric General Surgery, Pediatric Urology S..."
58,6,Emad SeifElnasr,Consultant General and Laparoscopic Surgery an...,General Surgery,Cleopatra,200.0,5,7.0,Waiting Time : 5 Minutes,https://www.vezeeta.com/en/dr/doctor-emad-seif...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Consultant in general, laparoscopic, and baria...","Intestinal Obstruction, Fistula, Hernia, Under...","Obesity Surgery, Abdominal Surgery, Endocrinal..."
59,6,Ehab Eltayeb,consultant of obstetrics and gynecology,Reproductive Medicine & Infertility,Mahatet El-Raml,400.0,5,6.0,Waiting Time : 10 Minutes,https://www.vezeeta.com/en/dr/doctor-ehab-elta...,https://cdn-dr-images.vezeeta.com/Assets/Image...,-Consultant in Obstetrics and Gynecology\r\n -...,NaN,"Gynaecology, IVF, Gynaecological Cosmetic Surg..."

In [31]:
pd.set_option('display.max_rows', 1000)
display(df[df['address']=='Shoubra El-Kheima'])

,page,name,description,Speciality,address,fee,rating,reviews_count,waiting_time,profile_url,image_url,about_doctor,symptoms_text,subspecialties_text
51,6,Moataz Abdelkhaliq,specialist,Dentistry,Shoubra El-Kheima,200.0,5,483.0,Waiting Time : 19 Minutes,https://www.vezeeta.com/en/dr/doctor-moataz-as...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Dentist specialized in fixed prosthodontics , ...",NaN,"Pediatric Dentistry, Orthodontics, Endodontics..."
185,19,mohamed mostafa amin,specialist of orthopedic surgery,Orthopedics,Shoubra El-Kheima,300.0,5,10.0,Waiting Time : 28 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-m...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Knee osteoarthritis treatment, Arthritis, Curv...","Arthroscopy and Sports injuries, Bone Deformit..."
223,23,essam farghaly,Gynecology and infertility specialist,Reproductive Medicine & Infertility,Shoubra El-Kheima,500.0,5,111.0,Waiting Time : 26 Minutes,https://www.vezeeta.com/en/dr/Doctor-essam-far...,https://cdn-dr-images.vezeeta.com/Assets/Image...,master degree in gynacology and obstatric and ...,"Vaginal Dryness, Dilation Of The Cervix, Pregn...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
565,57,Mona Elzematy,"Specialist in Oral Medicine and Surgery, Ortho...",Dentistry,Shoubra El-Kheima,200.0,5,13.0,Waiting Time : 17 Minutes,https://www.vezeeta.com/en/dr/doctor-mona-elze...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Oral and Dental Surgery Specialist\n\nAnd the ...,"Teeth whitening, Molar Pain, Bleeding Gums, Ro...","Endodontics, Periodontics, Oral and Maxillofac..."
703,72,Mohamed Awad,"Professor and consultant physiotherapy, obesit...",Physiotherapy and Sport Injuries,Shoubra El-Kheima,300.0,5,37.0,Waiting Time : 11 Minutes,https://www.vezeeta.com/en/dr/Doctor-Mohamed-A...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Consultant physiotherapy, obesity and thinness...","Arthritis, Rheumatoid Arthritis, Torn Ligament...","Pediatric Dietitian and Nutrition, Sport Injur..."
867,88,Islam Adel Awad,Consultant of Internal Medicine and Gastroente...,Internal Medicine,Shoubra El-Kheima,250.0,5,162.0,Waiting Time : 32 Minutes,https://www.vezeeta.com/en/dr/doctor-islam-ade...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Prof Dr / Islam Adel Awad\nConsultant of Inter...,"Gallbladder Pain, Convulsions, Fever, Vomittin...","Adult Diabetes and Endocrinology, Adult Hepato..."
916,93,Amal Abdelrauf Shafik,"Consultant of Dermatology , cosmetics and repr...",Dermatology,Shoubra El-Kheima,250.0,5,222.0,Waiting Time : 44 Minutes,https://www.vezeeta.com/en/dr/Doctor-Amal-Abde...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Acne, Skin Tags On The Face, Herpetic skin inf...","Genital Dermatology, Facial Plastic Surgery, A..."
942,96,Ibrahim farag khater,Specialist of Internal Medicine and Nephrology,Internal Medicine,Shoubra El-Kheima,250.0,5,747.0,Waiting Time : 28 Minutes,https://www.vezeeta.com/en/dr/doctor-ibrahem-f...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Specialist of int medicine and nephrology in m...,NaN,"Adult Hepatology, Adult Nephrology, Adult Gast..."
1172,119,Mohamed Karam,"Consultant in general internal medicine, diges...",Diabetes and Endocrinology,Shoubra El-Kheima,300.0,5,134.0,Waiting Time : 17 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-k...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Master of Internal Medicine, Al-Azhar Medicine...","High Testosterone, HbA1c control treatment, Pr...","Adult Diabetes and Endocrinology, Adult Hepato..."
1247,126,Ahmad Lashin,Obstetrics and gynecology consultant,Reproductive Medicine & Infertility,Shoubra El-Kheima,500.0,5,42.0,Waiting Time : 17 Minutes,https://www.vezeeta.com/en/dr/doctor-ahmad-las...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Obstetrics and gynecology consultant/\n Consul...,"Vaginal Dryness, Dilation Of The Cervix, Tumor...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
1252,127,Ahmad Lashin,Obstetrics and gynecology consultant,Reproductive Medicine & Infertility,Shoubra El-Kheima,500.0,5,42.0,Waiting Time : 17 Minutes,https://www.vezeeta.com/en/dr/doctor-ahmad-las...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Obstetrics and gynecology consultant/\n Consul...,"Vaginal Dryness, Dilation Of The Cervix, Tumor...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
1259,127,Mohamed Mosallam,consultant Obstetrics and Gynecology,Reproductive Medicine & Infertility,Shoubra El-Kheima,200.0,5,12.0,Waiting Time : 21 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-m...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Egyptian fellowship of Obstetrics and gynecolo...,"Vaginal Dryness, Dilation Of The Cervix, Pregn...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
1362,138,Manar Farouk,"senior consultant of internal medicine, aller...",Allergy and Immunology,Shoubra El-Kheima,250.0,5,72.0,Waiting Time : 14 Minutes,https://www.vezeeta.com/en/dr/doctor-manar-far...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Skin Spots, Lupus Erythematosus, Allergy, Chro...","Autoimmune Allergy, Respiratory Tract Allergy,..."
1495,151,Khalid Gamil,Senior Consultant and PhD in Internal Medicine...,Internal Medicine,Shoubra El-Kheima,450.0,5,19.0,Waiting Time : 43 Minutes,https://www.vezeeta.com/en/dr/doctor-khaled-ga...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Body Tremors, Gallbladder Pain, Stomach Pain, ...","Adult Diabetes and Endocrinology, Adult Hepato..."
1551,157,said mokhtar,"Senior consultant spine, bone and joint surgery",Orthopedics,Shoubra El-Kheima,250.0,5,30.0,Waiting Time : 6 Minutes,https://www.vezeeta.com/en/dr/doctor-said-mokh...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Senior Consultant of Spine, Bone and Joint Sur...","Knee osteoarthritis treatment, Arthritis, Curv...","Arthroscopy and Sports injuries, Adult Spine S..."
1668,168,George Salama,"Consultant of Ear, Nose and Throat",ENT,Shoubra El-Kheima,350.0,5,1067.0,Waiting Time : 28 Minutes,https://www.vezeeta.com/en/dr/Doctor-George-Sa...,https://cdn-dr-images.vezeeta.com/Assets/Image...,cosultant and chairman of depatment of ent,"Dizziness, Vocal Cords, Acute Otitis Media","Hearing and Balance Disorder, Adult Ear, Nose ..."
1810,184,Reem Fawzy Rashed,Specialist in Ophthalmology and Eye Surgery,Ophthalmology,Shoubra El-Kheima,250.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-reem-fawz...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Compound Hyperopic Astigmatism, Pimple On The ...","Adult Ophthalmology, Lasik, Vision Correction ..."
1859,188,Mohamed Arfat,Senior Professor and Consultant of General Sur...,General Surgery,Shoubra El-Kheima,250.0,5,50.0,Waiting Time : 17 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-a...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Master of General Surgery, Al-Azhar Medicine -...","Intestinal Obstruction, Fistula, Hernia, Under...","Pediatric General Surgery, Obesity Surgery, Ab..."
2291,232,Abd El Rahman Serry,Specialist in Oral Medicine and Dental Surgery,Dentistry,Shoubra El-Kheima,180.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-abd-el-ra...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Teeth whitening, TMJ Disorder, Molar Pain, Ble...","Endodontics, Periodontics, Orthodontics, Elder..."
2628,265,sherif Ramadan Abo EL Khier,"consultant obs , gyn. & urogynecology",Reproductive Medicine & Infertility,Shoubra El-Kheima,250.0,5,56.0,Waiting Time : 44 Minutes,https://www.vezeeta.com/en/dr/Doctor-sherif-Ab...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"consultant of obs., Gyne & Urogynecology in Ai...",NaN,"Gynaecology, IVF, Gynaecological Cosmetic Surg..."
2762,280,Mahmoud Abdallah,Consultant orthopedic surgery,Orthopedics,Shoubra El-Kheima,350.0,5,169.0,Waiting Time : 46 Minutes,https://www.vezeeta.com/en/dr/Doctor-Mahmoud-A...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,NaN,"Arthroscopy and Sports injuries, Bone Deformit..."
3464,351,Mohamed esam,"Specialist in physical therapy, rehabilitation...",Physiotherapy and Sport Injuries,Shoubra El-Kheima,150.0,5,15.0,Waiting Time : 24 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-e...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Physiotherapist and Nutritionist Faculty Of ph...,"Arthritis, Torn Ligaments, Rehabilitation, Clu...","Adult Dietitian and Nutrition, Adult Physiothe..."
3732,378,Islam Elsisi,Consultant and lecturer of masculinity surgeri...,Reproductive Medicine & Infertility,Shoubra El-Kheima,300.0,5,572.0,Waiting Time : 36 Minutes,https://www.vezeeta.com/en/dr/Doctor-islam-els...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Azoospermia, Urinary Incontinence, Teratozoosp...",Andrology
3989,403,Ahmed El Husseiny El Nemr,Specialist in orthopedic surgery,Orthopedics,Shoubra El-Kheima,250.0,5,47.0,Waiting Time : 24 Minutes,https://www.vezeeta.com/en/dr/doctor-ahmed-elh...,https://cdn-dr-images.vezeeta.com/Assets/Image...,_BACHELOR OF MEDICINE AND SURGERY\n\n_Master o...,"Osteoarthritis, Tarsal Tunnel Syndrome, Spinal...","Arthroscopy and Sports injuries, Adult Spine S..."
3996,404,Ahmed El Husseiny El Nemr,Specialist in orthopedic surgery,Orthopedics,Shoubra El-Kheima,250.0,5,47.0,Waiting Time : 24 Minutes,https://www.vezeeta.com/en/dr/doctor-ahmed-elh...,https://cdn-dr-images.vezeeta.com/Assets/Image...,_BACHELOR OF MEDICINE AND SURGERY\n\n_Master o...,"Osteoarthritis, Tarsal Tunnel Syndrome, Spinal...","Arthroscopy and Sports injuries, Adult Spine S..."
4168,421,Mohamed Abdelaziz,Ophthalmology consultant,Ophthalmology,Shoubra El-Kheima,200.0,5,355.0,Waiting Time : 28 Minutes,https://www.vezeeta.com/en/dr/Doctor-Mohamed-A...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Egyptian Fellowship Ophthalmology. ICO opht...,"Weak Vision, Eye Strain, Cataract","Pediatric Ophthalmology, Adult Ophthalmology, ..."
4213,426,Abdelhamid Atallah,"Professor M. consultant, First Orthopedic Surg...",Orthopedics,Shoubra El-Kheima,250.0,5,15.0,Waiting Time : 1 Hour and 23 Minutes,https://www.vezeeta.com/en/dr/doctor-abdelhami...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Professor of Orthopedic Surgery and Joints, Al...","Knee osteoarthritis treatment, Osteoarthritis,...","Foot and Ankle Orthopedics, Osteopathic Medici..."
4369,441,Eslam Ehab,Orthopedic Surgery Specialist,Orthopedics,Shoubra El-Kheima,180.0,5,15.0,Waiting Time : 1 Hour and 1 Minute,https://www.vezeeta.com/en/dr/doctor-eslam-eha...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Knee osteoarthritis treatment, Arm Pain, Neck ...","Osteopathic Medicine, Microscopic Surgery, Ped..."
4573,463,ElHusseiny ElSayed ElNemr,Internal and kidney diseases consultant. Endoc...,Internal Medicine,Shoubra El-Kheima,350.0,5,369.0,Waiting Time : 1 Hour and 13 Minutes,https://www.vezeeta.com/en/dr/doctor-elhussein...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Internal and kidney diseases consultant. Endoc...,"Gallbladder Pain, Convulsions, Fever, Vomittin...","Adult Diabetes and Endocrinology, Adult Nephro..."
4672,474,Mohamed Wageeh Sarhan,Consultant Of Cardiology and Vascular Surgery,Cardiology,Shoubra El-Kheima,400.0,5,195.0,Waiting Time : 2 Hours and 41 Minutes,https://www.vezeeta.com/en/dr/Doctor-Mohamed-W...,https://cdn-dr-images.vezeeta.com/Assets/Image...,MD Of Cardiology and Vascular Medicine \r\nMem...,"Heart Attack, Convulsions, Numbness Of The Per...","Adult Cardiology, Adult Vascular Diseases, Ped..."
4794,486,Mervat Mounir,Consultant of gynecology,Reproductive Medicine & Infertility,Shoubra El-Kheima,300.0,5,62.0,Waiting Time : 59 Minutes,https://www.vezeeta.com/en/dr/doctor-mervat--m...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"Consultant of obstetrics and gynecology, infer...",NaN,"Obstetrics, Gynaecological Cosmetic Surgery, G..."
5021,509,Hisham Ahmed AlWaseif,Nutrionanist,Dietitian and Nutrition,Shoubra El-Kheima,550.0,5,116.0,Waiting Time : 1 Hour and 35 Minutes,https://www.vezeeta.com/en/dr/Doctor-Hisham-Ah...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Dietetics Consultant\r\n\r\nConsultant - Physi...,NaN,"Adult Dietitian and Nutrition, Adult Physiothe..."
5193,526,Mahmoud Helmy Ramadan,"Rheumatic ,Bones & Joints Diseases Specialist",Rheumatology,Shoubra El-Kheima,350.0,5,64.0,Waiting Time : 22 Minutes,https://www.vezeeta.com/en/dr/Doctor-Mahmoud-H...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Rheumatism Specialist at the Military Hospital,NaN,"Adult Rheumatology, Pediatric Rheumatology, Ad..."
5451,552,Amr Akef,Specialist of orthopedic surgery,Orthopedics,Shoubra El-Kheima,350.0,5,510.0,Waiting Time : 35 Minutes,https://www.vezeeta.com/en/dr/doctor-amr-akef-...,https://cdn-dr-images.vezeeta.com/Assets/Image...,MSc Orthopaedics Cairo university \nSpecialist...,"Knee osteoarthritis treatment, Arthritis, Curv...","Arthroscopy and Sports injuries, Joint Replace..."
5641,571,Shaimaa Nasser,consultant of ophthalmology,Ophthalmology,Shoubra El-Kheima,200.0,5,590.0,Waiting Time : 29 Minutes,https://www.vezeeta.com/en/dr/Doctor-Shaimaa-N...,https://cdn-dr-images.vezeeta.com/Assets/Image...,M.B.B.CH at kasr el 3eny-master of ophthalmolo...,"Bilateral Cataracts, Color blindness, Weak Vis...","Adult Ophthalmology, Lasik, Vision Correction ..."
5775,585,Ahmed Ragab,Specialist in chest and tubric diseases,Chest and Respiratory,Shoubra El-Kheima,200.0,5,105.0,Waiting Time : 33 Minutes,https://www.vezeeta.com/en/dr/doctor-ahmed-rag...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Common Cold, Grunting, Asthma, Chest CT Scan, ...","Adult Allergy and Immunology, Pediatric Allerg..."
5776,585,Mieral Ouda,"Specialist in gynecology, obstetrics, infertil...",Reproductive Medicine & Infertility,Shoubra El-Kheima,300.0,5,10.0,Waiting Time : 11 Minutes,https://www.vezeeta.com/en/dr/doctor-mieral-ou...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Dilation Of The Cervix, Pain During Intercours...","Gynaecology, IVF, Gynaecological Cosmetic Surg..."
5852,593,Bahaa Mahmoud,"Consultant of Internal Medicine, Endocrinology...",Diabetes and Endocrinology,Shoubra El-Kheima,300.0,5,86.0,Waiting Time : 26 Minutes,https://www.vezeeta.com/en/dr/doctor-bahaa-mah...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Director of the Endocrinology and Diabetes Uni...,"High Testosterone, HbA1c control treatment, Sa...","Adult Diabetes and Endocrinology, Adult Intern..."
5940,604,Mohamed Ayman El Sayed,General Practitioner,ENT,Shoubra El-Kheima,180.0,5,20.0,Waiting Time : 21 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-a...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Fever, Tonsillitis, Mouth Ulcers, Tinnitus, Al...","Hearing and Balance Disorder, Adult Ear, Nose ..."
6133,623,Abdelrahman Gamal,Specialist of Internal Medicine,Internal Medicine,Shoubra El-Kheima,180.0,5,29.0,Waiting Time : 38 Minutes,https://www.vezeeta.com/en/dr/doctor-abdelrahm...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Specialist of Internal Medicine,"Gallbladder Pain, Common Cold, Stomach Pain, H...",Adult Internal Medicine
6140,624,Mohamed Salah,General Practitioner,Internal Medicine,Shoubra El-Kheima,180.0,5,22.0,Waiting Time : 42 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-s...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Gallbladder Pain, Convulsions, Fever, Vomittin...","Adult Diabetes and Endocrinology, Adult Hepato..."
6258,635,Ahmed Esmaeel Zidan,Specialist of Internal medicine,Internal Medicine,Shoubra El-Kheima,300.0,5,3.0,Waiting Time : 8 Minutes,https://www.vezeeta.com/en/dr/dr-ahmed-esmaeel...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"- Specialist in Internal Medicine, Diabetes, a...","Body Tremors, Gallbladder Pain, Fever, Common ...","Adult Hematology, Adult Diabetes and Endocrino..."
6431,653,Shaaban Kohel,Senior Consultant of Gynecology and Obstetrics,Reproductive Medicine & Infertility,Shoubra El-Kheima,300.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-shaaban-k...,https://cdn-dr-images.vezeeta.com/Assets/Image...,-Senior Consultant in Obstetrics and Gynecolog...,"Pregnancy, Postmenopausal Symptoms, Ectopic Pr...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
6880,698,Mostafa Darwish,General Practitioner,General Practice,Shoubra El-Kheima,180.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mostafa-d...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Laziness, Cramp, Fever, Sneezing, Hyperhidrosi...","Pediatric General Practice, Adult General Prac..."
6958,705,Reem El Gendy,Specialist in Oral Medicine and Dental Surgery,Dentistry,Shoubra El-Kheima,180.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-reem-el-g...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,NaN,"Adult Dentistry, Prosthodontics, Orthodontics,..."
6961,706,Mohamed moustafa Elnwagy,"Consultant and Lecturer of Cardiology, Vascula...",Cardiology,Shoubra El-Kheima,300.0,5,21.0,Waiting Time : 55 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-m...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Consultant in cardiovascular diseases and card...,"Heart Attack, Convulsions, Numbness Of The Per...",Adult Cardiology
7043,715,Shehab Samy,Neuro and brain surgery specialist,Neurosurgery,Shoubra El-Kheima,250.0,5,9.0,Waiting Time : 38 Minutes,https://www.vezeeta.com/en/dr/doctor-shehab-sa...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Convulsions, Swollen Feet, Peripheral Nerve In...","Adult Spine Surgery, Adult Neurology, Adult Ne..."
7099,720,Youmna Mostafa,ENT Specialist,ENT,Shoubra El-Kheima,180.0,5,5.0,Waiting Time : 54 Minutes,https://www.vezeeta.com/en/dr/doctor-youmna-mo...,https://cdn-dr-images.vezeeta.com/Assets/Image...,ENT Specialist,"Fever, Tonsillitis, Tinnitus, Adenoid, Flu, Th...","Pediatric Audiology, Adult Audiology, Hearing ..."
7124,723,Karim Wael,Specialist in Oral Medicine and Dental Surgery,Dentistry,Shoubra El-Kheima,180.0,5,3.0,Waiting Time : 55 Minutes,https://www.vezeeta.com/en/dr/doctor-karim-wae...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Bruxism, Teeth whitening, TMJ Disorder, Molar ...","Endodontics, Periodontics, Orthodontics, Prost..."
7486,760,osama ramadan,Consultant Eye and LASIK Surgery,Ophthalmology,Shoubra El-Kheima,200.0,5,150.0,Waiting Time : 21 Minutes,https://www.vezeeta.com/en/dr/doctor-osama-ram...,https://cdn-dr-images.vezeeta.com/Assets/Image...,- Consultant ophthalmology and surgery\r\n\r\n...,"Myopia, Pimple On The Eyelid, Corectopia, Reti...","Lasik, Vision Correction and Cataract"
7538,766,Rehab Helmy,Dermatology Consultant,Dermatology,Shoubra El-Kheima,250.0,5,10.0,Waiting Time : 29 Minutes,https://www.vezeeta.com/en/dr/doctor-rehab-hel...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Lip Filling, Hyperhidrosis, Boils In The Armpi...","Genital Dermatology, Facial Plastic Surgery, A..."
7597,772,Azza Abd El Hakim Huwaidy,Consultant Obstetrician and Gynecologist,Reproductive Medicine & Infertility,Shoubra El-Kheima,250.0,5,18.0,Waiting Time : 34 Minutes,https://www.vezeeta.com/en/dr/doctor-azza-abd-...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Dilation Of The Cervix, Pregnancy, Miscarriage...","Gynaecology, Obstetrics, IVF"
7747,787,Ahmed Zayed,Internal Medicine Specialist,Internal Medicine,Shoubra El-Kheima,180.0,5,5.0,Waiting Time : 1 Hour and 21 Minutes,https://www.vezeeta.com/en/dr/doctor-ahmed-zay...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Body Tremors, Gallbladder Pain, Convulsions, F...","Adult Diabetes and Endocrinology, Adult Hepato..."
7750,788,Ismail Mahdy,Specialist in Urology Surgery,Urology,Shoubra El-Kheima,180.0,5,17.0,Waiting Time : 26 Minutes,https://www.vezeeta.com/en/dr/doctor-ismail-ma...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"STD, Hematospermia, Nocturnal Enuresis, Microp...","Adult Urology, Adult Urology Surgery, Adult Ne..."

In [32]:
df[df['address'].isnull()]

,page,name,description,Speciality,address,fee,rating,reviews_count,waiting_time,profile_url,image_url,about_doctor,symptoms_text,subspecialties_text
12627,1280,Yosef yonis,"Consultant Vascular Surgery, Peripheral Cathet...",Vascular Surgery,NaN,500.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-yosef-yon...,https://cdn-dr-images.vezeeta.com/Assets/Image...,vasculer surgery consultant,NaN,"Pediatric Vascular Surgery, Adult Vascular Sur..."
14809,1500,Mohamed AL Hawy,specialist In Internal Medicine and emergency,Internal Medicine,NaN,70.0,5,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mohamed-e...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Specialist In Internal medicine And Emergency,NaN,"Adult Internal Medicine, Infectious Diseases"

In [33]:
df['address']= df['address'].fillna('Shoubra El-Kheima')

In [36]:
df = df[df['name'] != 'Mohamed AL Hawy']

### Fee Column

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17119 entries, 0 to 17119
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   page                 17119 non-null  int64
 1   name                 17119 non-null  object
 2   description          17110 non-null  object
 3   Speciality           17119 non-null  object
 4   address              17119 non-null  object
 5   fee                  17112 non-null  float64
 6   rating               17119 non-null  int64
 7   reviews_count        9685 non-null   float64
 8   waiting_time         9963 non-null   object
 9   profile_url          17119 non-null  object
 10  image_url            17119 non-null  object
 11  about_doctor         16577 non-null  object
 12  symptoms_text        12073 non-null  object
 13  subspecialties_text  17012 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [38]:
df['fee']= df['fee'].fillna(df['fee'].median())

### Rating column

In [39]:
df['rating'].value_counts()

rating
5    17119
Name: count, dtype: int64

In [40]:
df.drop(columns=['rating'], inplace=True)

In [41]:
df

,page,name,description,Speciality,address,fee,reviews_count,waiting_time,profile_url,image_url,about_doctor,symptoms_text,subspecialties_text
0,1,Mohamed Fateen Anous,Consultant of General and Laproscopic Surgery,General Surgery,New Cairo,600.0,37.0,Waiting Time : 26 Minutes,https://www.vezeeta.com/en/dr/doctor-mohamed-f...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Consultant of general and laparoscopic surgery,"Pilonidal Cyst, Intestinal Obstruction, Fistul...","Obesity Surgery, Abdominal Surgery, Adult Gast..."
1,1,Heba Hassan Hadhoud,"Specialist in oral and dental medicine, implan...",Dentistry,El-Rehab,200.0,608.0,Waiting Time : 14 Minutes,https://www.vezeeta.com/en/dr/doctor-heba--has...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Bruxism, Teeth whitening, TMJ Disorder, Molar ...","Pediatric Dentistry, Cosmetic Dentistry, Endod..."
2,1,Hoda Beder,"Consultant of Obstetrics, Gynecology and Infer...",Reproductive Medicine & Infertility,Tanta,150.0,131.0,Waiting Time : 22 Minutes,https://www.vezeeta.com/en/dr/doctor-hoda-bede...,https://cdn-dr-images.vezeeta.com/Assets/Image...,Dr. Huda Badir\n\n-PhD in Obstetrics and Gynec...,"Vaginal Dryness, Pregnancy, Placental Abruptio...","Gynaecologic Oncological Surgery, Obstetrics, ..."
3,1,Medhat higazi,"Specialist in root canal treatment, cosmetic d...",Dentistry,New Cairo,400.0,605.0,Waiting Time : 12 Minutes,https://www.vezeeta.com/en/dr/clinic-medhat--h...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"‎ -Bachelor of Oral and Dental Medicine, Ain S...","Bruxism, Teeth whitening, Molar Pain, Bleeding...","Cosmetic Dentistry, Endodontics, Periodontics,..."
4,1,Kareem Abdelfattah,Dental Cosmetic and restorative Specialist,Dentistry,El-Sheikh Zayed,400.0,84.0,Waiting Time : 9 Minutes,https://www.vezeeta.com/en/dr/doctor-kareem-ab...,https://cdn-dr-images.vezeeta.com/Assets/Image...,- Dr. Kareem Abdel Fattah holds a British fell...,"Bruxism, Teeth whitening, Molar Pain, Bleeding...","Cosmetic Dentistry, Endodontics, Periodontics,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17115,1732,nermin khaled,Physical Therapist and Sports Injury Specialist,Physiotherapy and Sport Injuries,El-Badrashin,300.0,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-nermin-kh...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,NaN,"Adult Dietitian and Nutrition, Adult Physiothe..."
17116,1732,Michael Murad,"Specialist in gynecology, obstetrics, infertil...",Reproductive Medicine & Infertility,El-Maadi,500.0,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-michael-m...,https://cdn-dr-images.vezeeta.com/Assets/Image...,"- Specialist in gynecology, obstetrics and inf...","Miscarriage, Ectopic Pregnancy, Breast Abscess...","Gynaecology, IVF, Gynaecologic Oncological Sur..."
17117,1732,Mostafa Fatooh,Nuclear Medicine & Oncology Specialist | Diagn...,Oncology,Dokki And Mohandessin,600.0,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mostafa-f...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,"Tumor, Salivary Gland Tumors, Parotid Tumors, ...","Adult Oncology, Pediatric Oncology, Radiation ..."
17118,1732,Mohamed Saleh Keshta,Urologist specialist,Urology,Roshdy,350.0,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mohamed-s...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,NaN,"Adult Urology, Adult Urology Surgery"
17119,1732,mostafa nady,Specialist in orthodontics and root canal trea...,Dentistry,El-Badrashin,200.0,NaN,NaN,https://www.vezeeta.com/en/dr/doctor-mostafa-n...,https://cdn-dr-images.vezeeta.com/Assets/Image...,#NAME?,NaN,"Cosmetic Dentistry, Endodontics, Periodontics,..."

### Review count column

In [43]:
df['reviews_count']= df['reviews_count'].fillna(0)

In [44]:
df['reviews_count']= df['reviews_count'].astype(int)

In [47]:
df['waiting_time'].value_counts()

waiting_time
Waiting Time : 8 Minutes                  568
Waiting Time : 13 Minutes                 442
Waiting Time : 11 Minutes                 371
Waiting Time : 14 Minutes                 355
Waiting Time : 18 Minutes                 355
Waiting Time : 10 Minutes                 339
Waiting Time : 15 Minutes                 331
Waiting Time : 23 Minutes                 330
Waiting Time : 17 Minutes                 317
Waiting Time : 12 Minutes                 290
Waiting Time : 16 Minutes                 284
Waiting Time : 19 Minutes                 280
Waiting Time : 20 Minutes                 256
Waiting Time : 9 Minutes                  245
Waiting Time : 26 Minutes                 226
Waiting Time : 21 Minutes                 222
Waiting Time : 28 Minutes                 206
Waiting Time : 24 Minutes                 205
Waiting Time : 22 Minutes                 196
Waiting Time : 25 Minutes                 187
Waiting Time : 29 Minutes                 171
Waiting Time : 27 Minutes                 155
Waiting Time : 32 Minutes                 149
Waiting Time : 33 Minutes                 144
Waiting Time : 30 Minutes                 143
Waiting Time : 35 Minutes                 139
Waiting Time : 34 Minutes                 126
Waiting Time : 31 Minutes                 122
Waiting Time : 36 Minutes                 122
Waiting Time : 40 Minutes                 110
Waiting Time : 37 Minutes                 108
Waiting Time : 38 Minutes                 102
Waiting Time : 39 Minutes                  94
Waiting Time : 45 Minutes                  94
Waiting Time : 42 Minutes                  84
Waiting Time : 43 Minutes                  80
Waiting Time : 7 Minutes                   77
Waiting Time : 41 Minutes                  76
Waiting Time : 46 Minutes                  71
Waiting Time : 51 Minutes                  62
Waiting Time : 44 Minutes                  62
Waiting Time : 52 Minutes                  59
Waiting Time : 50 Minutes                  56
Waiting Time : 49 Minutes                  56
Waiting Time : 47 Minutes                  52
Waiting Time : 1 Hour and 5 Minutes        51
Waiting Time : 48 Minutes                  48
Waiting Time : 6 Minutes                   43
Waiting Time : 55 Minutes                  41
Waiting Time : 56 Minutes                  41
Waiting Time : 53 Minutes                  37
Waiting Time : 1 Hour and 1 Minute         34
Waiting Time : 5 Minutes                   34
Waiting Time : 1 Hour and 10 Minutes       34
Waiting Time : 54 Minutes                  33
Waiting Time : 58 Minutes                  32
Waiting Time : 1 Hour                      31
Waiting Time : 1 Hour and 2 Minutes        30
Waiting Time : 1 Hour and 7 Minutes        29
Waiting Time : 1 Hour and 4 Minutes        28
Waiting Time : 59 Minutes                  27
Waiting Time : 57 Minutes                  24
Waiting Time : 8 دقائق                     23
Waiting Time : 1 Hour and 6 Minutes        22
Waiting Time : 1 Hour and 15 Minutes       21
Waiting Time : 1 Hour and 8 Minutes        20
Waiting Time : 1 Hour and 12 Minutes       17
Waiting Time : 1 Hour and 13 Minutes       17
Waiting Time : 1 Hour and 3 Minutes        17
Waiting Time : 1 Hour and 9 Minutes        16
Waiting Time : 1 Hour and 21 Minutes       16
Waiting Time : 1 Hour and 30 Minutes       15
Waiting Time : 13 دقيقة                    15
Waiting Time : 1 Hour and 18 Minutes       15
Waiting Time : 1 Hour and 16 Minutes       15
Waiting Time : 18 دقيقة                    14
Waiting Time : 1 Hour and 11 Minutes       13
Waiting Time : 1 Hour and 23 Minutes       13
Waiting Time : 1 Hour and 20 Minutes       12
Waiting Time : 1 Hour and 14 Minutes       12
Waiting Time : 3 Minutes                   11
Waiting Time : 1 Hour and 32 Minutes       11
Waiting Time : 1 Hour and 22 Minutes       11
Waiting Time : 1 Hour and 37 Minutes       11
Waiting Time : 1 Hour and 25 Minutes       11
Waiting Time : 1 Hour and 26 Minutes       11
Waiting Time : 1 Hour and 19 Minutes       10
Waiting Time : 15 دقيقة                    10
Waiting Time : 1 Hour and 17 Minutes       10
Waiting Time : 22 دقيقة                    10
Waiting Time : 4 Minutes                   10
Waiting Time : 11 دقيقة                     9
Waiting Time : 20 دقيقة                     9
Waiting Time : 9 دقائق                      9
Waiting Time : 1 Hour and 34 Minutes        9
Waiting Time : 24 دقيقة                     9
Waiting Time : 17 دقيقة                     9
Waiting Time : 35 دقيقة                     8
Waiting Time : 14 دقيقة                     8
Waiting Time : 29 دقيقة                     8
Waiting Time : 1 Hour and 31 Minutes        7
Waiting Time : 2 Hours                      7
Waiting Time : 1 Hour and 35 Minutes        7
Waiting Time : 1 Hour and 39 Minutes        7
Waiting Time : 21 دقيقة                     7
Waiting Time : 1 Hour and 43 Minutes        7
Waiting Time : 19 دقيقة                     7
Waiting Time : 1 Hour and 24 Minutes        7
Waiting Time : 1 Hour and 36 Minutes        6
Waiting Time : 1 Hour and 27 Minutes        6
Waiting Time : 33 دقيقة                     6
Waiting Time : 1 Hour and 42 Minutes        6
Waiting Time : 1 Hour and 56 Minutes        6
Waiting Time : 1 Hour and 51 Minutes        5
Waiting Time : 2 Hours and 17 Minutes       5
Waiting Time : 1 Hour and 49 Minutes        5
Waiting Time : 30 دقيقة                     5
Waiting Time : 28 دقيقة                     5
Waiting Time : 51 دقيقة                     5
Waiting Time : 1 Hour and 29 Minutes        5
Waiting Time : 12 دقيقة                     5
Waiting Time : 1 Hour and 40 Minutes        5
Waiting Time : 16 دقيقة                     4
Waiting Time : 10 دقائق                     4
Waiting Time : 23 دقيقة                     4
Waiting Time : 7 دقائق                      4
Waiting Time : 1 Hour and 48 Minutes        4
Waiting Time : 32 دقيقة                     4
Waiting Time : 37 دقيقة                     4
Waiting Time : 27 دقيقة                     4
Waiting Time : 2 Hours and 27 Minutes       3
Waiting Time : 26 دقيقة                     3
Waiting Time : 38 دقيقة                     3
Waiting Time : 1 Hour and 33 Minutes        3
Waiting Time : 45 دقيقة                     3
Waiting Time : 1 Hour and 38 Minutes        3
Waiting Time : 44 دقيقة                     3
Waiting Time : 1 Hour and 44 Minutes        3
Waiting Time : 31 دقيقة                     3
Waiting Time : ساعة و 4 دقائق               3
Waiting Time : 3 Hours and 18 Minutes       2
Waiting Time : 6 دقائق                      2
Waiting Time : 3 Hours and 14 Minutes       2
Waiting Time : 3 Hours and 6 Minutes        2
Waiting Time : 2 Hours and 4 Minutes        2
Waiting Time : 41 دقيقة                     2
Waiting Time : 4 Hours and 6 Minutes        2
Waiting Time : 3 Hours and 46 Minutes       2
Waiting Time : 2 Hours and 24 Minutes       2
Waiting Time : ساعة و 6 دقائق               2
Waiting Time : 2 Hours and 7 Minutes        2
Waiting Time : ساعة و 9 دقائق               2
Waiting Time : 9 Hours and 46 Minutes       2
Waiting Time : 5 Hours and 19 Minutes       2
Waiting Time : 6 Hours and 11 Minutes       2
Waiting Time : 2 Hours and 2 Minutes        2
Waiting Time : 1 Hour and 41 Minutes        2
Waiting Time : 1 Hour and 28 Minutes        2
Waiting Time : 2 Hours and 21 Minutes       2
Waiting Time : 39 دقيقة                     2
Waiting Time : 50 دقيقة                     2
Waiting Time : 11 Hours and 40 Minutes      2
Waiting Time : 1 Hour and 47 Minutes        2
Waiting Time : 2 Hours and 56 Minutes       2
Waiting Time : 2 Hours and 16 Minutes       2
Waiting Time : 1 Hour and 45 Minutes        2
Waiting Time : 1 Hour and 46 Minutes        2
Waiting Time : 3 Hours                      2
Waiting Time : 2 Hours and 19 Minutes       2
Waiting Time : 43 دقيقة                     2
Waiting Time : 53 دقيقة                     2
Waiting Time : 2 Hours and 1 Minute         2
Waiting Time : 42 دقيقة                     2
Waiting Time : ساعة و 8 دقائق               2
Waiting Time : 49 دقيقة                     2
Waiting Time : 25 دقيقة                     2
Waiting Time : ساعة و 13 دقيقة              2
Waiting Time : 1 Hour and 58 Minutes        2
Waiting Time : 3 Hours and 51 Minutes       1
Waiting Time : 2 Hours and 35 Minutes       1
Waiting Time : 1 Minute                     1
Waiting Time : 2 Hours and 10 Minutes       1
Waiting Time : 7 Hours and 20 Minutes       1
Waiting Time : ساعة و 5 دقائق               1
Waiting Time : 2 Hours and 50 Minutes       1
Waiting Time : دقيقتين                      1
Waiting Time : ساعة و 42 دقيقة              1
Waiting Time : ساعة و 17 دقيقة              1
Waiting Time : 2 Minutes                    1
Waiting Time : ساعة و 12 دقيقة              1
Waiting Time : 3 Hours and 45 Minutes       1
Waiting Time : 5 Hours                      1
Waiting Time : 11 Hours and 16 Minutes      1
Waiting Time : 5 Hours and 47 Minutes       1
Waiting Time : 11 Hours and 11 Minutes      1
Waiting Time : ساعة و 34 دقيقة              1
Waiting Time : 3 Hours and 8 Minutes        1
Waiting Time : 8 Hours and 32 Minutes       1
Waiting Time : 4 Hours and 27 Minutes       1
Waiting Time : 5 Hours and 22 Minutes       1
Waiting Time : 58 دقيقة                     1
Waiting Time : 4 Hours and 8 Minutes        1
Waiting Time : 20 Hours and 29 Minutes      1
Waiting Time : 2 Hours and 51 Minutes       1
Waiting Time : 1 Hour and 53 Minutes        1
Waiting Time : 3 Hours and 1 Minute         1
Waiting Time : 2 Hours and 6 Minutes        1
Waiting Time : 5 Hours and 13 Minutes       1
Waiting Time : 5 Hours and 36 Minutes       1
Waiting Time : 1 Hour and 59 Minutes        1
Waiting Time : 3  ساعات و 46 دقيقة          1
Waiting Time : 4 Hours and 57 Minutes       1
Waiting Time : 3 Hours and 3 Minutes        1
Waiting Time : 2 Hours and 48 Minutes       1
Waiting Time : 19 Hours and 19 Minutes      1
Waiting Time : 2 Hours and 13 Minutes       1
Waiting Time : 6 Hours and 56 Minutes       1
Waiting Time : 3 Hours and 4 Minutes        1
Waiting Time : 13 Hours and 13 Minutes      1
Waiting Time : 3 Hours and 59 Minutes       1
Waiting Time : 5 Hours and 32 Minutes       1
Waiting Time : 2 Hours and 36 Minutes       1
Waiting Time : 52 دقيقة                     1
Waiting Time : 2 Hours and 25 Minutes       1
Waiting Time : ساعتين و 25 دقيقة            1
Waiting Time : 2 Hours and 53 Minutes       1
Waiting Time : 47 دقيقة                     1
Waiting Time : 36 دقيقة                     1
Waiting Time : 2 Hours and 55 Minutes       1
Waiting Time : 2 Hours and 23 Minutes       1
Waiting Time : 2 Hours and 30 Minutes       1
Waiting Time : ساعة و 21 دقيقة              1
Waiting Time : ساعة و 14 دقيقة              1
Waiting Time : 4 Hours and 58 Minutes       1
Waiting Time : 3 Hours and 11 Minutes       1
Waiting Time : ساعة و 24 دقيقة              1
Waiting Time : ساعة و دقيقتين               1
Waiting Time : 5 Hours and 6 Minutes        1
Waiting Time : 2 Hours and 52 Minutes       1
Waiting Time : ساعة و دقيقة                 1
Waiting Time : 3 Hours and 35 Minutes       1
Waiting Time : ساعة و 30 دقيقة              1
Waiting Time : 3 Hours and 39 Minutes       1
Waiting Time : 34 دقيقة                     1
Waiting Time : 2 Hours and 41 Minutes       1
Waiting Time : 2 Hours and 11 Minutes       1
Waiting Time : 1 Hour and 54 Minutes        1
Waiting Time : 9 Hours and 15 Minutes       1
Waiting Time : 3 Hours and 49 Minutes       1
Waiting Time : 1 Hour and 55 Minutes        1
Waiting Time : 2 Hours and 5 Minutes        1
Waiting Time : 3 Hours and 37 Minutes       1
Waiting Time : 3 Hours and 12 Minutes       1
Waiting Time : 4 Hours and 21 Minutes       1
Waiting Time : ساعة و 44 دقيقة              1
Waiting Time : ساعة و 16 دقيقة              1
Waiting Time : ساعة و 10 دقائق              1
Waiting Time : 46 دقيقة                     1
Waiting Time : ساعة و 15 دقيقة              1
Waiting Time : 12 Hours and 55 Minutes      1
Waiting Time : 7  ساعات و 29 دقيقة          1
Waiting Time : 54 دقيقة                     1
Waiting Time : 4 Hours and 56 Minutes       1
Waiting Time : 48 دقيقة                     1
Waiting Time : ساعة و 7 دقائق               1
Waiting Time : ساعة و 32 دقيقة              1
Waiting Time : 4 Hours and 30 Minutes       1
Waiting Time : 2 Hours and 32 Minutes       1
Waiting Time : 20 Hours and 37 Minutes      1
Name: count, dtype: int64

In [50]:
import re

def extract_minutes(value):
    if pd.isna(value):
        return np.nan
    text = str(value).strip().lower()
    if not text or text in {'nan', 'n/a', 'none', 'no waiting time'}:
        return np.nan

    # Convert hours to minutes first, if present
    hour_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:h|hr|hour|hours)", text)
    if hour_match:
        return float(hour_match.group(1)) * 60

    # Extract the first minute value; handles "10-15 min", "15 mins", "up to 20 minutes"
    minute_match = re.search(r"(\d+(?:\.\d+)?)\s*(?:m|min|mins|minute|minutes)", text)
    if minute_match:
        return float(minute_match.group(1))

    # If only a numeric range is present without units, take the average
    range_match = re.search(r"(\d+(?:\.\d+)?)\D+(\d+(?:\.\d+)?)", text)
    if range_match:
        return (float(range_match.group(1)) + float(range_match.group(2))) / 2

    # Fallback to any number present
    num_match = re.search(r"(\d+(?:\.\d+)?)", text)
    if num_match:
        return float(num_match.group(1))

    return np.nan

# Create a numeric waiting time in minutes
if 'waiting_time_min' not in df.columns:
    df['waiting_time_min'] = df['waiting_time'].apply(extract_minutes)
else:
    df['waiting_time_min'] = df['waiting_time'].apply(extract_minutes)

print("Extracted waiting_time_min as numeric minutes.")
print(df[['waiting_time', 'waiting_time_min']].head(10))

Extracted waiting_time_min as numeric minutes.
                waiting_time  waiting_time_min
0  Waiting Time : 26 Minutes              26.0
1  Waiting Time : 14 Minutes              14.0
2  Waiting Time : 22 Minutes              22.0
3  Waiting Time : 12 Minutes              12.0
4   Waiting Time : 9 Minutes               9.0
5  Waiting Time : 20 Minutes              20.0
6  Waiting Time : 12 Minutes              12.0
7   Waiting Time : 9 Minutes               9.0
8                        NaN               NaN
9                        NaN               NaN

In [52]:
df['waiting_time_min'].value_counts()

waiting_time_min
60.0      670
8.0       593
13.0      459
11.0      380
18.0      370
14.0      364
10.0      344
15.0      342
23.0      334
17.0      327
12.0      296
16.0      289
19.0      287
20.0      265
9.0       256
21.0      230
26.0      229
24.0      215
28.0      211
22.0      206
25.0      190
29.0      179
27.0      159
32.0      154
33.0      150
30.0      149
35.0      147
34.0      128
31.0      125
36.0      123
37.0      112
40.0      110
38.0      105
45.0       97
39.0       96
42.0       87
7.0        82
43.0       82
41.0       78
46.0       72
51.0       67
44.0       66
52.0       60
50.0       58
49.0       58
47.0       53
120.0      51
48.0       49
6.0        47
55.0       41
56.0       41
53.0       39
5.0        35
54.0       34
58.0       33
59.0       27
57.0       24
180.0      23
4.0        13
3.0        11
300.0       9
240.0       9
660.0       4
360.0       3
540.0       3
1200.0      2
24.5        1
780.0       1
480.0       1
1.0         1
1140.0      1
2.0         1
720.0       1
420.0       1
Name: count, dtype: int64

In [53]:
df=df.drop(columns=['waiting_time'])

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17119 entries, 0 to 17119
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   page                 17119 non-null  int64
 1   name                 17119 non-null  object
 2   description          17110 non-null  object
 3   Speciality           17119 non-null  object
 4   address              17119 non-null  object
 5   fee                  17119 non-null  float64
 6   reviews_count        17119 non-null  int32
 7   profile_url          17119 non-null  object
 8   image_url            17119 non-null  object
 9   about_doctor         16577 non-null  object
 10  symptoms_text        12073 non-null  object
 11  subspecialties_text  17012 non-null  object
 12  waiting_time_min     9960 non-null   float64
dtypes: float64(2), int32(1), int64(1), object(9)
memory usage: 1.8+ MB

In [55]:
df['waiting_time_min'].fillna(-1, inplace=True)

C:\Users\7520\AppData\Local\Temp\ipykernel_25192\1472807048.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['waiting_time_min'].fillna(-1, inplace=True)

In [56]:
df['waiting_time_min'].rename('Waiting Time (Minutes)', inplace=True)

0        26.0
1        14.0
2        22.0
3        12.0
4         9.0
         ...
17115    -1.0
17116    -1.0
17117    -1.0
17118    -1.0
17119    -1.0
Name: Waiting Time (Minutes), Length: 17119, dtype: float64

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17119 entries, 0 to 17119
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   page                 17119 non-null  int64
 1   name                 17119 non-null  object
 2   description          17110 non-null  object
 3   Speciality           17119 non-null  object
 4   address              17119 non-null  object
 5   fee                  17119 non-null  float64
 6   reviews_count        17119 non-null  int32
 7   profile_url          17119 non-null  object
 8   image_url            17119 non-null  object
 9   about_doctor         16577 non-null  object
 10  symptoms_text        12073 non-null  object
 11  subspecialties_text  17012 non-null  object
 12  waiting_time_min     17119 non-null  float64
dtypes: float64(2), int32(1), int64(1), object(9)
memory usage: 1.8+ MB

In [58]:
df.to_csv(r"D:\Big_Data_Project\Cleaned_Data\cleaned_data.csv", index=False)